// Build-time generator: distills a real English dictionary (SCOWL-derived
// `wordlist-english`) into a curated, tiered word bank for TYPEBLITZ.
//
//   npm install --no-save wordlist-english && node scripts/gen-words.mjs
//
// Tiers 10/20/35 are the "most common" SCOWL buckets, so words stay
// recognizable and fun to type instead of obscure dictionary filler.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

const SOURCES = [
  { tier: 10, weight: 0 },
  { tier: 20, weight: 1 },
  { tier: 35, weight: 2 },
];

// Exact-match blocklist (profanity / slurs / unpleasant themes).
const BLOCK = new Set(`
ass asses arse arsehole bastard bitch bitches bitching bollocks boob boobs bugger
crap crappy cunt damn damned dick dicks dickhead dildo dyke fag faggot fart farted farting
fuck fucked fucker fucking goddamn hell homo horny jerk jizz kike nigga nigger nude nudes
orgasm orgy penis piss pissed pissing poop porn porno prick pube pubes puke queer rape raped
raping rapist retard retarded scrotum semen sex sexed sexes sexier sexiest sexual sexy shit
shits shitted shitting shitty slut sluts spic tit tits titties titty turd twat vagina wanker
whore whores wop
kill killed killer killers killing kills murder murdered murderer murdering murders
suicide suicides rapes molest molested molester nazi nazis
`.trim().split(/\s+/));

// Severe substrings — catch inflected forms not in the exact list.
const BLOCK_SUBSTR = ["fuck", "shit", "cunt", "nigg", "faggot", "rape", "rapist", "whore", "slut", "porn", "molest", "suicid"];

const seen = new Map(); // word -> best (lowest) weight

for (const { tier, weight } of SOURCES) {
  const words = require(`wordlist-english/english-words-${tier}.json`);
  for (const raw of words) {
    const w = String(raw);
    if (!/^[a-z]{3,12}$/.test(w)) continue;       // pure lowercase a-z, sane length
    if (BLOCK.has(w)) continue;
    if (BLOCK_SUBSTR.some((s) => w.includes(s))) continue;
    if (/(.)\1\1/.test(w)) continue;              // triple letters = likely junk
    if (!/[aeiouy]/.test(w)) continue;            // must be pronounceable
    const prev = seen.get(w);
    if (prev === undefined || weight < prev) seen.set(w, weight);
  }
}

// Bucket by length; within a bucket, most-common words first.
const BUCKETS = [
  { name: "T0", min: 3, max: 4, cap: 700 },
  { name: "T1", min: 5, max: 6, cap: 1700 },
  { name: "T2", min: 7, max: 8, cap: 1900 },
  { name: "T3", min: 9, max: 12, cap: 1500 },
];

const all = [...seen.entries()].map(([w, weight]) => ({ w, weight }));
const out = {};
let total = 0;

for (const b of BUCKETS) {
  const pool = all
    .filter((e) => e.w.length >= b.min && e.w.length <= b.max)
    .sort((a, z) => a.weight - z.weight || a.w.localeCompare(z.w))
    .slice(0, b.cap)
    .map((e) => e.w)
    .sort();
  out[b.name] = pool;
  total += pool.length;
  console.log(`${b.name} (${b.min}-${b.max} chars): ${pool.length}`);
}

console.log("TOTAL:", total);

// Emit space-delimited strings — far smaller than JSON arrays after minify.
const body = BUCKETS.map(
  (b) => `const ${b.name} = "${out[b.name].join(" ")}".split(" ");`
).join("\n\n");

mkdirSync("src/game", { recursive: true });
writeFileSync(
  "src/game/dictionary.ts",
  `// AUTO-GENERATED by scripts/gen-words.mjs — do not edit by hand.
// Source: wordlist-english (SCOWL), commonness tiers 10/20/35, filtered for
// typeability and family-friendliness. ${total} words total.
/* eslint-disable */

${body}

/** Word pools bucketed by length: T0 = 3-4 chars ... T3 = 9-12 chars. */
export const TIERS: readonly (readonly string[])[] = [T0, T1, T2, T3];
export const TOTAL_WORDS = ${total};
`
);

console.log("Wrote src/game/dictionary.ts");
